Repository codesquad-members-2023-group5/issue-tracker, pull requests merged in 2023-06, with the labels that each got.

#160 [FE] Refactor: data key name 수정
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListItem/List.stories.jsx
  FE/src/components/IssueList/IssueListMain/IssueListItem/index.jsx
  FE/src/components/LabelList/LabelListMain/LabelListItem/index.jsx
  FE/src/components/LabelList/LabelListMain/index.jsx
  FE/src/components/LabelList/LabelTable/index.jsx
  FE/src/components/Milestone/MilestoneMain/MilestoneListItem/index.jsx
  FE/src/components/Milestone/MilestoneMain/index.jsx
  FE/src/components/Milestone/MilestoneTable/index.jsx
  FE/src/components/NewIssueForm/index.jsx
  FE/src/components/common/DropDown/index.jsx
  FE/src/components/common/Label/Label.stories.jsx
  FE/src/components/common/Label/index.jsx
  FE/src/components/common/SideBar/SideBar.stories.jsx
  FE/src/components/common/SideBar/SideBarMenu/SelectedItem/index.jsx
  FE/src/mocks/json/issueData.json
  FE/src/mocks/json/labelData.json
  FE/src/mocks/json/userData.json
  FE/src/mocks/mockAPIHandler.js
  FE/src/mocks/mockData.js
  FE/src/utils/index.js
Labels: ♻️ refactoring, 🧑‍💻 FE

#161 [FE] 지금까지 작업한 MSW 내용 풀리퀘
  FE/.eslintrc.js
  FE/src/assets/Icons/archive.svg
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/style.js
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/LabelList/LabelListMain/LabelListItem/index.jsx
  FE/src/components/Milestone/MilestoneMain/MilestoneListItem/index.jsx
  FE/src/components/common/Button/style.js
  FE/src/constants/api.js
  FE/src/context/checkBoxContext.jsx
  FE/src/hooks/useFetch.js
  FE/src/mocks/mockAPIHandler.js
  FE/src/mocks/mockData.js
  FE/src/pages/IssueDetail/index.jsx
  FE/src/pages/IssueList/index.jsx
Labels: ✨ feat, 🧑‍💻 FE

#167 Devfe/msw
  .github/workflows/main.yml
  FE/.eslintrc.js
  FE/src/App.jsx
  FE/src/assets/Icons/archive.svg
  FE/src/components/Header/index.jsx
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/style.js
  FE/src/components/IssueList/IssueListHeader/FilterBar/index.jsx
  FE/src/components/IssueList/IssueListHeader/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListItem/List.stories.jsx
  FE/src/components/IssueList/IssueListMain/IssueListItem/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/style.js
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/IssueList/IssueListMain/style.js
  FE/src/components/LabelList/LabelListMain/LabelListItem/index.jsx
  FE/src/components/LabelList/LabelListMain/index.jsx
  FE/src/components/LabelList/LabelTable/index.jsx
  FE/src/components/Milestone/MilestoneHeader/index.jsx
  FE/src/components/Milestone/MilestoneMain/MilestoneListItem/index.jsx
  FE/src/components/Milestone/MilestoneMain/index.jsx
  FE/src/components/Milestone/MilestoneTable/index.jsx
  FE/src/components/NewIssueForm/index.jsx
  FE/src/components/NewIssueForm/style.js
  FE/src/components/common/Button/index.jsx
  FE/src/components/common/Button/style.js
  FE/src/components/common/DropDown/DropDownMenu/index.jsx
  FE/src/components/common/DropDown/DropDownMenu/style.js
  FE/src/components/common/DropDown/index.jsx
  FE/src/components/common/DropDown/style.js
  FE/src/components/common/Label/Label.stories.jsx
  FE/src/components/common/Label/index.jsx
  FE/src/components/common/Label/style.js
  FE/src/components/common/SideBar/SideBar.stories.jsx
  FE/src/components/common/SideBar/SideBarMenu/SelectedItem/index.jsx
  FE/src/components/common/SideBar/SideBarMenu/index.jsx
  FE/src/components/common/SideBar/SideBarMenu/style.js
  FE/src/components/common/SideBar/index.jsx
  FE/src/components/common/TextArea/index.jsx
  FE/src/components/common/TextArea/style.js
  FE/src/components/common/TextInput/index.jsx
  FE/src/components/common/TextInput/style.js
  FE/src/constants/api.js
  FE/src/context/checkBoxContext.jsx
  FE/src/context/filterContext.jsx
  FE/src/context/filterReducer.js
  FE/src/hooks/useFetch.js
  FE/src/mocks/json/issueData.json
  FE/src/mocks/json/labelData.json
  FE/src/mocks/json/userData.json
  FE/src/mocks/mockAPIHandler.js
  FE/src/mocks/mockData.js
  FE/src/pages/IssueDetail/index.jsx
  FE/src/pages/IssueList/index.jsx
  FE/src/utils/index.js
  FE/src/utils/isEqualObj.js
Labels: 🔧 chore, 🧑‍💻 FE

#168 [BE] comment-api 브랜치를 release 브랜치로 병합
  BE/.gitignore
  BE/src/main/java/team05/codesquad/issuetracker/controller/CommentController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/CommentDto.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/request/CommentCreateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/request/CommentUpdateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/response/CommentCreateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/response/CommentDtoListResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/response/CommentUpdateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/response/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/CommentRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MemberRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/CommentService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MilestoneService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/main/resources/static/docs/api-docs.adoc
Labels: ✨ feat, 🧑‍💻 BE

#172 [FE] Feat: Filter Bar 기능 구현
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/index.jsx
  FE/src/components/IssueList/IssueListHeader/FilterBar/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListItem/index.jsx
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/LabelList/LabelTable/index.jsx
  FE/src/components/common/DropDown/DropDownMenu/index.jsx
  FE/src/components/common/DropDown/index.jsx
  FE/src/components/common/TabButton/style.js
  FE/src/context/filterContext.jsx
  FE/src/context/filterReducer.js
  FE/src/mocks/mockData.js
  FE/src/utils/index.js
  FE/src/utils/randomColor.js
  FE/src/utils/time.js
  FE/src/utils/validator.js
Labels: ✨ feat, 🧑‍💻 FE

#178 이슈, 마일스톤, 라벨, 담당자 API 기능 구현
  BE/README.md
  BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
  BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/team05/codesquad/issuetracker/config/CorsConfigurer.java
  BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/CommentController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/HomeController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/MemberController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/ResponseData.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/CommentDto.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/request/CommentCreateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/request/CommentUpdateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/response/CommentCreateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/response/CommentDtoListResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/commentdto/response/CommentUpdateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/request/IssueRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/response/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/request/LabelRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/memberdto/response/MemberResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/memberdto/response/MembersResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/request/MilestoneUpdateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneUpdateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/member/Assignee.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/CommentRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/LabelRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MemberRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/CommentService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MemberService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MilestoneService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: ♻️ refactoring, 🧑‍💻 BE
