Repository codesquad-members-2023-group5/issue-tracker, pull requests merged in 2023-05, with the labels that each got.

#20 [FE] Feat: Header 컴포넌트의 user 이미지 style 적용
  FE/src/components/Header/style.js
  FE/src/styles/color.js
Labels: ✨ feat, 🧑‍💻 FE

#46 Feat/fe/filter bar
  FE/.eslintrc.js
  FE/.storybook/preview.js
  FE/public/assets/alertCircle.svg
  FE/public/assets/archive.svg
  FE/public/assets/calendar.svg
  FE/public/assets/checkBoxActive.svg
  FE/public/assets/checkBoxDisable.svg
  FE/public/assets/checkBoxInitial.svg
  FE/public/assets/checkOffCircle.svg
  FE/public/assets/checkOnCircle.svg
  FE/public/assets/chevronDown.svg
  FE/public/assets/edit.svg
  FE/public/assets/label.svg
  FE/public/assets/milestone.svg
  FE/public/assets/paperclip.svg
  FE/public/assets/plus.svg
  FE/public/assets/refreshCcw.svg
  FE/public/assets/search.svg
  FE/public/assets/smile.svg
  FE/public/assets/trash.svg
  FE/public/assets/userImg.svg
  FE/public/assets/xSquare.svg
  FE/src/App.jsx
  FE/src/assets/Icons/alertCircle.svg
  FE/src/assets/Icons/archive.svg
  FE/src/assets/Icons/calendar.svg
  FE/src/assets/Icons/checkBoxActive.svg
  FE/src/assets/Icons/checkBoxDisable.svg
  FE/src/assets/Icons/checkBoxInitial.svg
  FE/src/assets/Icons/checkOffCircle.svg
  FE/src/assets/Icons/checkOnCircle.svg
  FE/src/assets/Icons/chevronDown.svg
  FE/src/assets/Icons/edit.svg
  FE/src/assets/Icons/label.svg
  FE/src/assets/Icons/milestone.svg
  FE/src/assets/Icons/paperclip.svg
  FE/src/assets/Icons/plus.svg
  FE/src/assets/Icons/refreshCcw.svg
  FE/src/assets/Icons/search.svg
  FE/src/assets/Icons/smile.svg
  FE/src/assets/Icons/trash.svg
  FE/src/assets/Icons/xSquare.svg
  FE/src/assets/defaultLogo.svg
  FE/src/assets/loginLogo.svg
  FE/src/components/Header/Header.stories.jsx
  FE/src/components/Header/index.jsx
  FE/src/components/IssueList/FilterBar/FilterBar.stories.jsx
  FE/src/components/IssueList/FilterBar/index.jsx
  FE/src/components/IssueList/FilterBar/style.js
  FE/src/components/common/Icon/IconComponents.jsx
  FE/src/components/common/Icon/index.jsx
  FE/src/index.jsx
  FE/src/mocks/mockData.js
  FE/src/styles/GlobalStyles.js
  FE/src/styles/color.js
  FE/src/styles/font.js
  FE/src/styles/theme.js
Labels: ✨ feat, 🧑‍💻 FE

#48 ✨ feat: 탭버튼 컴포넌트 완성
  FE/src/components/common/Icon/IconComponents.jsx
  FE/src/components/common/TabButton/TabButton.stories.jsx
  FE/src/components/common/TabButton/index.jsx
  FE/src/components/common/TabButton/style.js
Labels: ✨ feat, 🧑‍💻 FE

#58 [FE] Refactor: Button 컴포넌트
  FE/src/components/common/Button/Button.stories.jsx
  FE/src/components/common/Button/index.jsx
  FE/src/components/common/Button/style.js
Labels: ✨ feat, 🧑‍💻 FE

#59 [BE] Spring Data JDBC 사용과 로컬 DB 테스트 진행을 위한 초기 설정
  BE/application.properties
  BE/src/main/java/team05/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/team05/codesquad/issuetracker/repository/IssueRepositoryTest.java
Labels: 🧑‍💻 BE

#67 [FE] Feat: 이슈리스트 메인
  FE/src/assets/Icons/checkBoxActive.svg
  FE/src/assets/Icons/checkBoxDisable.svg
  FE/src/components/IssueList/IssueListHeader/NavButtons/style.js
  FE/src/components/IssueList/IssueListHeader/style.js
  FE/src/components/IssueList/IssueListMain/List/List.stories.jsx
  FE/src/components/IssueList/IssueListMain/List/index.jsx
  FE/src/components/IssueList/IssueListMain/List/style.js
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/IssueList/IssueListMain/style.js
  FE/src/components/common/Label/Label.stories.jsx
  FE/src/components/common/Label/index.jsx
  FE/src/components/common/Label/style.js
  FE/src/mocks/mockData.js
  FE/src/styles/GlobalStyles.js
Labels: ✨ feat, 🧑‍💻 FE

#69 [FE] Feat: Issue List Main Header 컴포넌트 생성
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/DropDownButton/DropDownButton.stories.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/DropDownButton/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/DropDownButton/style.js
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/IssueListMainHeader.stories.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/style.js
Labels: ✨ feat, 🧑‍💻 FE

#70 [BE] API 명세서 작성을 위한 REST Docs 초기 설정 build.gradle에 추가
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/src/main/java/team05/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MemberService.java
Labels: 🔧 chore

#72 [BE] label Entity 구현
  BE/application.properties
  BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/LabelRepository.java
Labels: ✨ feat, 🧑‍💻 BE

#73 [BE] Milestone Entity 구현
  BE/src/main/java/team05/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MilestoneRepository.java
Labels: ✨ feat, 🧑‍💻 BE

#74 [BE] Comment Entity 구현
  BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/CommentRepository.java
Labels: ✨ feat, 🧑‍💻 BE

#76 [iOS] 이슈 목록 CollectionView 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/CustomLabelView.swift
  iOS/issue-tracker/issue-tracker/IssueCardCell.swift
  iOS/issue-tracker/issue-tracker/IssueListHeaderView.swift
  iOS/issue-tracker/issue-tracker/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/SFsymbol.swift
  iOS/issue-tracker/issue-tracker/TabBarType.swift
  iOS/issue-tracker/issue-tracker/TabBarViewController.swift
Labels: 🧑‍💻 iOS

#75 [iOS] Feat: issue filter view setting
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/FontStyle.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterCell.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterHeaderCell.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterViewController.swift
Labels: ✨ feat, 🧑‍💻 iOS

#79 [BE] S3 연결성공
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/Member.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MemberRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MemberService.java
  BE/src/main/resources/application.properties
  BE/src/test/java/team05/codesquad/issuetracker/repository/IssueRepositoryTest.java
Labels: ✨ feat, 🧑‍💻 BE

#91 [FE] Feat: 초기 Input 컴포넌트 생성
  FE/src/components/common/Input/Input.stories.jsx
  FE/src/components/common/Input/index.jsx
  FE/src/components/common/Input/style.js
Labels: ✨ feat, 🧑‍💻 FE

#96 [BE] Label api 구현
  BE/src/main/java/team05/codesquad/issuetracker/auth/AWSCredentialsProperties.java
  BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
  BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelsResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/LabelRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
  BE/src/main/resources/schema.sql
Labels: ✨ feat, 🧑‍💻 BE

#98 [FE] Feat: dropdown 클릭하면 닫히는 기능 및 filter된 issue가 없으면 메시지 띄우는 기능 구현
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/IssueList/IssueListMain/style.js
  FE/src/components/common/DropDown/index.jsx
Labels: ✨ feat, 🧑‍💻 FE

#103 [FE] Feat: textarea 컴포넌트 생성 및 Input 컴포넌트 수정
  FE/src/components/common/Input/Input.stories.jsx
  FE/src/components/common/Input/index.jsx
  FE/src/components/common/Input/style.js
  FE/src/components/common/TextArea/index.jsx
  FE/src/components/common/TextArea/style.js
  FE/src/components/common/TextArea/textArea.stories.jsx
Labels: ✨ feat, 🧑‍💻 FE

#106 Feat: 네트워크 로직 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/HTTPHandler.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueListSectionData.swift
Labels: ✨ feat, 🧑‍💻 iOS

#108 feat: Diffable DataSource 및 CellRegistration 적용
  iOS/issue-tracker/issue-tracker/IssueList/IssueCardCell.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueListHeaderView.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueViewController.swift
Labels: ✨ feat, 🧑‍💻 iOS

#110 Feat/be/issue api
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelsResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/IssueRefLabel.java
  BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
Labels: ✨ feat, 🧑‍💻 BE

#109 Feat/ios/issue filter collection view diffable datasource
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterCell.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterHeaderView.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IssueFilterViewController.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/IsuueFilterData.swift
  iOS/issue-tracker/issue-tracker/IssueFilter/MockHeaderData.swift
Labels: ✨ feat, 🧑‍💻 iOS

#113 Feat/be/issue api
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssuesResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/IssueRefLabel.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: 🧑‍💻 BE

#115 Feat: StackView 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/IssueList/CustomCapsuleLabel.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueCardCell.swift
  iOS/issue-tracker/issue-tracker/IssueList/IssueViewController.swift
Labels: ✨ feat, 🧑‍💻 iOS

#118 feat: issue에 milestone 연결
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: 🧑‍💻 BE

#119 [FE] 이슈 디테일 페이지 UI 완료
  FE/src/App.jsx
  FE/src/assets/Icons/grip.svg
  FE/src/components/Header/style.js
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailHeader/style.js
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/style.js
  FE/src/components/IssueDetail/IssueDetailMain/Comments/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/style.js
  FE/src/components/IssueDetail/IssueDetailMain/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/style.js
  FE/src/components/IssueList/IssueListMain/List/index.jsx
  FE/src/components/common/Icon/IconComponents.jsx
  FE/src/components/common/Label/index.jsx
  FE/src/components/common/Label/style.js
  FE/src/components/common/SideBar/SideBarMenu/SelectedItem/index.jsx
  FE/src/components/common/SideBar/SideBarMenu/SelectedItem/style.js
  FE/src/components/common/SideBar/SideBarMenu/index.jsx
  FE/src/components/common/SideBar/index.jsx
  FE/src/components/common/SideBar/style.js
  FE/src/components/common/TextArea/style.js
  FE/src/mocks/json/issueData.json
  FE/src/mocks/json/labelData.json
  FE/src/mocks/json/userData.json
  FE/src/mocks/mockAPIHandler.js
  FE/src/mocks/mockData.js
  FE/src/pages/DetailIssue/index.jsx
  FE/src/pages/DetailIssue/style.js
  FE/src/pages/IssueDetail/index.jsx
  FE/src/pages/IssueDetail/style.js
  FE/src/styles/GlobalStyles.js
Labels: ✨ feat, 🧑‍💻 FE

#120 [FE] Feat: 이슈 작성 페이지
  FE/src/App.jsx
  FE/src/components/IssueList/IssueListHeader/NavButtons/index.jsx
  FE/src/components/NewIssueForm/index.jsx
  FE/src/components/NewIssueForm/style.js
  FE/src/components/common/DropDown/index.jsx
  FE/src/components/common/TextArea/index.jsx
  FE/src/components/common/TextArea/style.js
  FE/src/components/common/TextInput/style.js
  FE/src/pages/NewIssue/index.jsx
  FE/src/pages/NewIssue/style.js
Labels: ✨ feat, 🧑‍💻 FE

#124 [FE] Feat: 새로운 이슈 작성 페이지 UI 구성 및 리팩토링 진행
  FE/src/App.jsx
  FE/src/components/Header/index.jsx
  FE/src/components/Header/style.js
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailHeader/style.js
  FE/src/components/IssueList/IssueListHeader/FilterBar/style.js
  FE/src/components/IssueList/IssueListHeader/NavButtons/index.jsx
  FE/src/components/IssueList/IssueListHeader/NavButtons/style.js
  FE/src/components/IssueList/IssueListHeader/index.jsx
  FE/src/components/IssueList/IssueListHeader/style.js
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/DropDownButton/DropDownButton.stories.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/DropDownButton/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/DropDownButton/style.js
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/style.js
  FE/src/components/IssueList/IssueListMain/List/index.jsx
  FE/src/components/IssueList/IssueListMain/List/style.js
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/common/DropDown/DropDownMenu/index.jsx
  FE/src/components/common/TabButton/index.jsx
  FE/src/components/common/TabButton/style.js
  FE/src/components/common/TextInput/index.jsx
  FE/src/context/filterContext.jsx
  FE/src/context/themeContext.jsx
  FE/src/hooks/useTheme.js
  FE/src/styles/color.js
  FE/src/utils/index.js
Labels: ✨ feat, 🧑‍💻 FE

#126 Refactor: 이슈 디테일 페이지 코딩컨벤션에 맞게 리팩토링 진행.
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailHeader/style.js
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/style.js
  FE/src/components/IssueDetail/IssueDetailMain/Comments/style.js
  FE/src/components/IssueDetail/IssueDetailMain/index.jsx
  FE/src/components/common/TextInput/style.js
  FE/src/pages/IssueDetail/index.jsx
  FE/src/pages/IssueDetail/style.js
Labels: ♻️ refactoring, 🧑‍💻 FE

#128 [FE] Refactor: IssueListMain 컴포넌트에서 List와 관련된 네이밍 변경
  FE/src/components/IssueList/IssueListMain/IssueListItem/List.stories.jsx
  FE/src/components/IssueList/IssueListMain/IssueListItem/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListItem/style.js
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/IssueList/IssueListMain/style.js
Labels: ♻️ refactoring, 🧑‍💻 FE

#130 [FE] Feat: 마일스톤 페이지 기능 추가
  FE/.eslintrc.js
  FE/src/components/Milestone/MilestoneMain/index.jsx
  FE/src/components/Milestone/MilestoneMain/style.js
  FE/src/mocks/mockData.js
Labels: ✨ feat, 🧑‍💻 FE

#131 [FE] Feat: 초기 LabelList UI 완료
  FE/src/App.jsx
  FE/src/components/LabelList/LabelListHeader/index.jsx
  FE/src/components/LabelList/LabelListHeader/style.js
  FE/src/components/LabelList/LabelListMain/LabelListItem/index.jsx
  FE/src/components/LabelList/LabelListMain/LabelListItem/style.js
  FE/src/components/LabelList/LabelListMain/index.jsx
  FE/src/components/LabelList/LabelListMain/style.js
  FE/src/components/LabelList/LabelTable/index.jsx
  FE/src/components/LabelList/LabelTable/style.js
  FE/src/components/common/TextInput/index.jsx
  FE/src/pages/LabelList/index.jsx
  FE/src/pages/LabelList/style.js
Labels: ✨ feat, 🧑‍💻 FE

#145 [BE] issue, label, milestone API 구현,배포
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradlew.bat
  BE/src/main/java/team05/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
  BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/request/IssueRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/response/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/response/IssuesResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/request/LabelRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/response/LabelResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/response/LabelsResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/MilestoneDto.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/request/MilestoneCreateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/request/MilestoneUpdateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneCreateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneListResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneUpdateResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/IssueRefLabel.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/IssueRowMapper.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/CommentRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/LabelRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MemberRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MemberService.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MilestoneService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/team05/codesquad/issuetracker/IssueTrackerApplicationTests.java
  BE/src/test/java/team05/codesquad/issuetracker/controller/IssueControllerTest.java
  BE/src/test/java/team05/codesquad/issuetracker/repository/IssueRepositoryTest.java
Labels: 🧑‍💻 BE

#146 [FE] Feat: 마일스톤 페이지 API 적용 완료
  FE/src/App.jsx
  FE/src/components/Milestone/MilestoneHeader/index.jsx
  FE/src/components/Milestone/MilestoneMain/MilestoneListItem/index.jsx
  FE/src/components/Milestone/MilestoneMain/index.jsx
  FE/src/components/Milestone/MilestoneTable/index.jsx
  FE/src/constants/api.js
  FE/src/index.jsx
  FE/src/mocks/mockAPIHandler.js
  FE/src/pages/Milestone/index.jsx
  FE/vercel.json
Labels: ✨ feat, 🧑‍💻 FE

#148 [BE] Milestone-API 작업 완료
  BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/MilestoneDto.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/request/MilestoneUpdateRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneWithIssuesResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/java/team05/codesquad/issuetracker/service/MilestoneService.java
Labels: ✨ feat, 🧑‍💻 BE

#149 Deploy: 프론트엔드 마일스톤, 레이블 페이지까지 API 연결 성공
  FE/src/components/LabelList/LabelListHeader/index.jsx
  FE/src/components/LabelList/LabelListHeader/style.js
  FE/src/components/LabelList/LabelListMain/LabelListItem/index.jsx
  FE/src/components/LabelList/LabelListMain/LabelListItem/style.js
  FE/src/components/LabelList/LabelListMain/index.jsx
  FE/src/components/LabelList/LabelListMain/style.js
  FE/src/components/LabelList/LabelTable/index.jsx
  FE/src/components/LabelList/LabelTable/style.js
  FE/src/components/Milestone/MilestoneHeader/index.jsx
  FE/src/components/Milestone/MilestoneMain/MilestoneListItem/index.jsx
  FE/src/components/Milestone/MilestoneMain/index.jsx
  FE/src/components/Milestone/MilestoneMain/style.js
  FE/src/components/Milestone/MilestoneTable/index.jsx
  FE/src/components/Milestone/MilestoneTable/style.js
  FE/src/constants/api.js
  FE/src/index.jsx
  FE/src/mocks/mockAPIHandler.js
  FE/src/pages/LabelList/index.jsx
  FE/src/pages/Milestone/index.jsx
  FE/src/utils/generateRandomColor.js
  FE/vercel.json
Labels: 🧑‍💻 FE, 🙌🏻 Common

#152 [BE] 누락된 jar 파일 추가를 위한 머지
  .idea/.gitignore
  .idea/issue-tracker.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  BE/.gitignore
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
  BE/src/main/resources/data.sql
Labels: 🔧 chore, 🧑‍💻 BE

#156 [FE] Refactor: New Issue 페이지 리펙토링 및 msw에 post 하기
  FE/src/components/IssueDetail/IssueDetailHeader/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/Comment/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/Comments/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/index.jsx
  FE/src/components/IssueDetail/IssueDetailMain/style.js
  FE/src/components/NewIssueForm/index.jsx
  FE/src/components/NewIssueForm/style.js
  FE/src/components/common/SideBar/SideBarMenu/index.jsx
  FE/src/components/common/SideBar/SideBarMenu/style.js
  FE/src/components/common/SideBar/index.jsx
  FE/src/mocks/mockAPIHandler.js
  FE/src/mocks/mockData.js
  FE/src/pages/IssueDetail/index.jsx
Labels: ♻️ refactoring, 🧑‍💻 FE

#158 [FE] Feat: 체크박스 헤더 갈아끼우기 까지 완료
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/index.jsx
  FE/src/components/IssueList/IssueListMain/IssueListMainHeader/style.js
  FE/src/components/IssueList/IssueListMain/index.jsx
  FE/src/components/IssueList/IssueListMain/style.js
  FE/src/components/common/Button/index.jsx
  FE/src/components/common/DropDown/DropDownMenu/index.jsx
  FE/src/constants/api.js
  FE/src/context/filterContext.jsx
  FE/src/context/filterReducer.js
  FE/src/utils/isEqualObj.js
Labels: ✨ feat, 🧑‍💻 FE

#159 [BE] FE와 키네임 맞추기, 변수 삭제, 수정
  .idea/.gitignore
  .idea/issue-tracker.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  BE/.gitignore
  BE/build.sh
  BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/request/IssueRequest.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/response/IssueResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/response/LabelResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/response/LabelsResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/MilestoneDto.java
  BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/response/MilestoneListResponse.java
  BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
  BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/team05/codesquad/issuetracker/controller/IssueControllerTest.java
Labels: 🧑‍💻 BE, 🙌🏻 Common
